# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tictactoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TICTACTOE(object):
    def setupUi(self, TICTACTOE):
        TICTACTOE.setObjectName("TICTACTOE")
        TICTACTOE.resize(660, 950)
        self.centralwidget = QtWidgets.QWidget(TICTACTOE)
        self.centralwidget.setObjectName("centralwidget")

        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(230, 770, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("background-color:rgba(60, 148, 255);\\n\n"
"border:1px solid rgba(0,0,0,0);\\n\n"
"border-bottom-color:rgba(46,82,101,255);\\n\n"
"color:rgb(60, 148, 255)\\n\n"
"                                ")
        self.reset.setObjectName("reset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(175, 680, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")

        TICTACTOE.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TICTACTOE)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 26))
        self.menubar.setObjectName("menubar")
        TICTACTOE.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TICTACTOE)
        self.statusbar.setObjectName("statusbar")
        TICTACTOE.setStatusBar(self.statusbar)

        self.retranslateUi(TICTACTOE)
        QtCore.QMetaObject.connectSlotsByName(TICTACTOE)

    def retranslateUi(self, player1):
        _translate = QtCore.QCoreApplication.translate
        player1.setWindowTitle(_translate("TICTACTOE", "TİC-TAC-TOE"))
        self.reset.setText(_translate("reset", "Reset"))
